[package]
name = "spectra"
version = "0.6.0"
license = "BSD-3-Clause"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]
description = "Demoscene framework"
keywords = ["demoscene", "animation", "graphics"]

homepage = "https://github.com/phaazon/spectra"
repository = "https://github.com/phaazon/spectra"
documentation = "https://docs.rs/spectra"

build = "build.rs"

[[bin]]
name = "spectra"
path = "spectra/src/main.rs"
doc = false

[dependencies]
alto = "1.1"
any-cache = "0.2"
cgmath = "0.14"
chrono = "0.3"
clap = "2.19"
luminance = "0.22"
luminance-glfw = "0.3"
image = "0.13"
glsl = "0.6.0"
notify = "4.0"
num-traits = "0.1"
rusttype = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
vorbis = "0.1"
wavefront_obj = "5.0"

[dependencies.nom]
version = "3.2"
features = ["verbose-errors"]

[dev-dependencies]
rand = "0.3" # for unit tests
